# Use existing docker image as base
FROM swkhodocker/bionic:latest as bionic_base

# Download & install depedency
RUN cat /etc/lsb-release
RUN tail -f /dev/null

# Tell the image what to do when it starts as a container
#CMD ["cat /etc/lsb-release"]

